#!/usr/bin/env node
/**
 * Inlines the generated app email templates into a TypeScript module.
 *
 *   pnpm build:emails
 *
 * ── Why inline them ─────────────────────────────────────────
 * The templates live in `email-templates/templates/app/`, outside `src/`, so
 * Next never bundles them — reading them at runtime with `fs` works locally and
 * then fails on a serverless deploy where only traced files ship. Turning them
 * into a `.ts` module makes them ordinary imports that the bundler follows.
 *
 * Runs after `email-templates/build.mjs`, which is what actually renders the
 * HTML. This only carries the result across the boundary.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE_DIR = join(process.cwd(), "email-templates", "templates", "app");
const OUT_FILE = join(
  process.cwd(),
  "src",
  "backend",
  "modules",
  "auth",
  "infrastructure",
  "email",
  "templates.generated.ts",
);

/** Filename → export name and the subject line that goes with it. */
const TEMPLATES = [
  {
    file: "verify-email.html",
    export: "VERIFY_EMAIL",
    subject: "Confirm your email address for Jobak",
  },
  {
    file: "reset-password.html",
    export: "RESET_PASSWORD",
    subject: "Reset your Jobak password",
  },
] as const;

/** Escapes a string for a TypeScript template literal. */
const escape = (html: string) =>
  html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const parts = TEMPLATES.map((t) => {
  const html = readFileSync(join(SOURCE_DIR, t.file), "utf8");

  if (!html.includes("{{link}}")) {
    throw new Error(
      `${t.file} has no {{link}} placeholder — the sender would mail a button that goes nowhere.`,
    );
  }

  return `export const ${t.export} = {
  subject: ${JSON.stringify(t.subject)},
  html: \`${escape(html)}\`,
} as const;`;
});

const output = `/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Produced by scripts/build-email-templates.mts from the HTML in
 * email-templates/templates/app/, which is itself generated by
 * email-templates/build.mjs.
 *
 * To change an email: edit email-templates/build.mjs, then run
 *   node email-templates/build.mjs && pnpm build:emails
 */

${parts.join("\n\n")}
`;

writeFileSync(OUT_FILE, output, "utf8");
console.log(
  `Inlined ${TEMPLATES.length} templates (${output.length} bytes) -> ${OUT_FILE}`,
);
